'''
This script takes ASCII files of specific glacier extent which may have data values outside of the catchment area, and "clips" 
them to the extent of the catchment defined in the WaSiM project. Needs an existing subcatchment file (ending in ".ezg").

'''
#import libraries
import numpy as np
import os
import rasterio

#set path of working directory
path = os.getcwd() 

#set directory paths and filenames
#path to the WaSiM initialization folder
WaSiM_initialization_folder = 'initfolder'
#path to the observations folder, or wherever the glacier raster files are located
project_observations_folder = 'observations_folder'
#path to the WaSiM input folder
WaSiM_input_folder = 'inputfolder'
#filename for the observed glacier raster file that needs to be processed
glacier_file = 'glacier.asc'
#filename for the WaSiM subcatchment raster generated by TANALYS
subcatchment_identification_file = 'subcatchments.ezg'

def glacier_raster_write(observations_folder, initialization_folder, input_folder, glacier_sample, subcatchment_identification):
    
    #opens the glacier raster
    glacier_ds = rasterio.open(os.path.join(observations_folder, glacier_sample)) #
    glacier = glacier_ds.read(1)
    
    #set data values to 1
    #observed_glaciers_0 = observed_glaciers.copy()
    glacier[glacier >= 0] = 1
    
    #open subcatchment raster ezg
    subcatchments_ds = rasterio.open(os.path.join(input_folder, subcatchment_identification))
    subcatchments = subcatchments_ds.read(1)
    #make copy with data values set to 0 
    subcatchments_zeroed = subcatchments.copy()
    subcatchments_zeroed[subcatchments_zeroed >= 0] = 0
    
    #add glc raster and zeroed subcatchment raster
    catchment_glacier =  glacier + subcatchments_zeroed
    #set all negative values to WaSiM nodata value (-9999)
    catchment_glacier[catchment_glacier < 0] = -9999
    
    #print rasters
    #set profile
    kwds_subcatchments = subcatchments_ds.profile
    
    #glacier raster file write
    catchment_glacier_file = rasterio.open(os.path.join(initialization_folder, 'glacier_1.asc'), 'w', **kwds_subcatchments)
    catchment_glacier_file.write(catchment_glacier, 1)
    catchment_glacier_file.close()
    
    glacier_ds.close()
    subcatchments_ds.close()
    #end function

#run function
initialization_glacier_rasters(project_observations_folder, WaSiM_initialization_folder, WaSiM_input_folder, glacier_sample, subcatchment_identification_file)


#end!






