'''
A script that takes a glacier cover raster, "clips" it to the extent of your catchment in your WaSiM project,
then creates the glc and glid raster files from it. Created when ArcGIS functions were frustrating me.
Requires an existing subcatchment raster, (file extension ".ezg"), from TANALYS.

'''
#import libraries
import numpy as np
import os
import rasterio

#set directory paths and filenames
#path to your WaSiM initialization folder
WaSiM_initialization_folder = 'yourinitfolder'
#path to your WaSiM input folder
WaSiM_input_folder = 'yourinputfolder'
#filename for the observed glacier raster file that your are trying to process
observed_glacier_cover_file = 'yourglaciers.asc'
#filename for the WaSiM subcatchment raster generated by TANALYS
subcatchment_identification_file = 'yoursubcatchments.ezg'

#define function for entire process

def initialization_glacier_rasters(initialization_folder, input_folder, observed_glacier_cover, subcatchment_identification):

    #opens your raster of observed glacier extent
    observed_glaciers_ds = rasterio.open(os.path.join(initialization_folder, observed_glacier_cover))
    observed_glaciers = observed_glaciers_ds.read(1)
    
    #set data values to 1
    #observed_glaciers_0 = observed_glaciers.copy()
    observed_glaciers[observed_glaciers >= 0] = 1
    
    #open subcatchment raster ezg
    subcatchments_ds = rasterio.open(os.path.join(input_folder, subcatchment_identification))
    subcatchments = subcatchments_ds.read(1)
    #make copy with data values set to 0 
    subcatchments_zeroed = subcatchments.copy()
    subcatchments_zeroed[subcatchments_zeroed >= 0] = 0
    
    #add glc raster and zeroed subcatchment raster
    catchment_glacier_cover =  observed_glaciers + subcatchments_zeroed
    #set all negative values to nodata values of -9999
    catchment_glacier_cover[catchment_glacier_cover < 0] = -9999
    #make copy of glc ezg raster with data values set to 0
    catchment_glacier_cover_zeroed = catchment_glacier_cover.copy()
    catchment_glacier_cover_zeroed[catchment_glacier_cover_zeroed > 0] = 0
    #add subcatchment raster to zeroed glc ezg raster to get glid raster
    catchment_glacier_identification = catchment_glacier_cover_zeroed + subcatchments
    #set all negative values to nodata values of -9999
    catchment_glacier_identification[catchment_glacier_identification < 0] = -9999 
    
    #print rasters
    #set profile
    kwds_subcatchments = subcatchments_ds.profile
    
    #glacier cover raster file write
    catchment_glacier_cover_file = rasterio.open(os.path.join(initialization_folder, 'your_glc.asc'), 'w', **kwds_subcatchments)
    catchment_glacier_cover_file.write(catchment_glacier_cover,1)
    catchment_glacier_cover_file.close()
    #glacier identification raster file write
    catchment_glacier_identification_file = rasterio.open(os.path.join(initialization_folder, 'your_glid.asc'), 'w', **kwds_subcatchments)
    catchment_glacier_identification_file.write(catchment_glacier_identification,1)
    catchment_glacier_identification_file.close()
    
    observed_glaciers_ds.close()
    subcatchments_ds.close()
    #end function


initialization_glacier_rasters(WaSiM_initialization_folder, WaSiM_input_folder, observed_glacier_cover_file, subcatchment_identification_file)

#end






